'use strict'

export default {
  TOGGLE_ASIDE: 'TOGGLE_ASIDE',
  GET_POST_BY_ID: 'GET_POST_BY_ID',
  GET_POST_SINGLE_SUCCESS: 'GET_POST_SINGLE_SUCCESS',
  GET_POST_SINGLE_ERROR: 'GET_POST_SINGLE_ERROR'
}
